echo ""
echo ""
echo ""
echo ""
echo "if you get stuck in a loop of 'default: Warning: Authentication failure. Retrying...' try removing ~/vagrant.d/insecure_private_key"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "if you get stuck in a loop of 'default: Warning: Authentication failure. Retrying...' try removing ~/vagrant.d/insecure_private_key"
echo ""
echo ""
echo ""
echo ""
vagrant box add --name dfdevm_nodeschool ./box/dfdevm_nodeschool.box
vagrant up