# Shown with default settings, modify these or add other configurations
# in the same way you would modify any vagrant file

Vagrant.configure(2) do |config|
  config.vm.box = "dfdevm_nodeschool"
  config.vm.network "private_network", ip: "192.168.33.33"
  config.ssh.insert_key=false

  # change your side - the first arg - 
  # but leave the second arg alone, as it is created in Chef 
  config.vm.synced_folder "~/work/nodeschool", "/home/vagrant/nodeschool", group: "vagrant", owner: "vagrant"
  config.vm.synced_folder "~/shuttle", "/home/vagrant/shuttle", group: "vagrant", owner: "vagrant"


  # adjust memory to suit your machine and your usage
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
  SHELL
end
